setwd("/Users/adammcmillion/Desktop/Evolution/Tasks/Project")
read.csv("hepaBsex.csv")
hepabsex<-read.csv("hepaBsex.csv")
read.csv("Rates of hepatitis B by state.csv")
Hepabratesbystate<-read.csv("Rates of hepatitis B by state.csv")
read.csv("Newely reported hepatitis C virus by sex and age.csv")
reportedhepaCbysex<-read.csv("Newely reported hepatitis C virus by sex and age.csv")
read.csv("Hepatitis C State and rate.csv")
hepaCstateandrate<-read.csv("Hepatitis C State and rate.csv")
read.csv("Hepatitis C ethnicity.csv")
hepaCethnicity<-read.csv("Hepatitis C ethnicity.csv")
read.csv("Hepatitis C state rate.csv")
hepaCstaterate<-read.csv("Hepatitis C state rate.csv")
read.csv("hepatitis C age group.csv")
hepaCagegroup<-read.csv("hepatitis C age group.csv")
read.csv("Hepatitis A states ongoing outbreak.csv")
HepaAongoing<-read.csv("Hepatitis A states ongoing outbreak.csv")
read.csv("Hepatitis A States end outbreak.csv")
HepaAonend<-read.csv("Hepatitis A States end outbreak.csv")
read.csv("Hepatitis A rate by age.csv")
HepAratebyage<- read.csv("Hepatitis A rate by age.csv")
read.csv("HepatitisAagerate 2006.csv")
year06agerate<-read.csv("HepatitisAagerate 2006.csv")
read.csv("Hepatitis A agerate07.csv")
hepAagerate07<-read.csv("Hepatitis A agerate07.csv")
read.csv("Hepatitis A rateyear08.csv")
hepAagerate08<-read.csv("Hepatitis A rateyear08.csv")
read.csv("hepatitis rateage09.csv")
hepAagerate09<-read.csv("hepatitis rateage09.csv")
read.csv("Hepattis A rateage10.csv")
hepAagerate10<-read.csv("Hepattis A rateage10.csv")
read.csv("hepatitisagerate11.csv")
hepAagerate11<-read.csv("hepatitisagerate11.csv")
read.csv("hepatitisAagerate12.csv")
hepAagerate12<-read.csv("hepatitisAagerate12.csv")
read.csv("Hepatitisagerate13.csv")
hepAagerate13<-read.csv("Hepatitisagerate13.csv")
read.csv("Hepatitis C state rate .csv")
us_mapdata<-read.csv("Hepatitis C state rate .csv")
read.csv("pratice usmap.csv")
practice<-read.csv("pratice usmap.csv")
read.csv("Hepatitis c 19 rates.csv")
hepaC19rates<-read.csv("Hepatitis c 19 rates.csv")
read.csv("Hepatitis C rates 2020.csv")
hepaC20rates<-read.csv("Hepatitis C rates 2020.csv")
read.csv("Hepatitis B rates 2020.csv")
hepaB20rates<-read.csv("Hepatitis B rates 2020.csv")
read.csv("Hepatitis B 2016.csv")
hepaB16rates<-read.csv("Hepatitis B 2016.csv")

