setwd("/Users/adammcmillion/Desktop/Evolution/Tasks/Task_08")
library(phytools)
help(phytools)
trees<-list()
births<-vector()
Fractions<-vector()
random<-c()
random2<-c()
treelist<-c()
for(i in 1:100){
  births[i]<-runif(1)
  Fractions[i]<-runif(1)
  trees[[i]]<-pbtree(b=births[i], d=(Fractions[i]*births[i]), n=100)
  random[[i]]<-births[i]
  random2[[i]]<-(Fractions[i])
  treelist[[i]]<-mean(trees[[i]]$edge.length)
}
pdf('Trees.pdf')
plot(trees[[i]])
dev.off()
sapply(trees,Ntip)
tips<-log(sapply(trees,Ntip))
random3<-unlist(random)
head(tips)
pdf("log tips & Diversification question 4. pdf")
plot(tips, xlab="log of tips", ylab=" net diversification")
dev.off()
?cor
cor(tips,random3)
random4<-unlist(random2)
treelist2<-unlist(treelist)
plot(treelist2, random3, ylab="speciation rate", xlab="Average branch length",pch=4)
pdf("speciation rate and average branch length.pdf")
plot(treelist2, random3, ylab="speciation rate", xlab="Average branch length", pch=1)
dev.off()
cor(treelist2,random4)
Tree<-trees[[which.max(tips)]]
pdf("Tree.pdf")
plot(Tree)
dev.off()
rates<-vector()
traits<-c()
meantraits<-c()
vartraits<-c()
for(i in 1:100){
  rates[i]<-runif(1)
traits[[i]]<-fastBM(tree=Tree, sig2=rates[i])  
meantraits[[i]]<-mean(traits[[i]])
vartraits[[i]]<-var(traits[[i]])
}
meantraits<-unlist(meantraits)
pdf("rates of meantratis.pdf")
plot(meantraits,rates)
dev.off()
cor(meantraits, rates)
#The correlation was 0.0599, which is telling us it is less related tot he variant.
vartraits<-unlist(vartraits)
pdf("rate of vartraits.pdf")
plot(vartraits,rates)
dev.off()
cor(vartraits,rates)
#The correlation was 0.739, which is telling us it is more closely related to the variant.
pdf("08_plot.pdf")
plot(traits[[1]], traits[[2]])
dev.off()
cor(traits[[1]],traits[[2]])
#The correlation test was 0.111
traitMat<-cbind(traits[[1]], traits[[4]])


#Extra credit:
pdf("08EC plot.pdf")
phylomorphospace(Tree, traitMat, xlab="Trait 1", ylab="Trait 2")
dev.off()
